[project]
name = "isacg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = [
    "gradio",
    "httpx>=0.28.1",
    "onnx>=1.18.0",
    "onnxruntime>=1.22.0",
    "pillow",
    "tensorboard>=2.19.0",
    "torch==2.7.0",
    "torchvision",
    "tqdm",
]
