[project]
name = "isacg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = [
    "gradio",
    "httpx",
    "onnx",
    "onnxruntime",
    "pillow",
    "tensorboard",
    "torch==2.7.0",
    "torchvision",
    "tqdm",
]
